apiVersion: logic.kubesmarts.org/v1
kind: LogicFlowDefinition
metadata:
  labels:
    app.kubernetes.io/name: logic-operator
    app.kubernetes.io/managed-by: kustomize
  name: sleepy-workflow-v1-0-0
spec:
  runtimeRef:
    name: hello-runtime
  flow:
    document:
      dsl: '1.0.0'
      namespace: examples
      name: sleepy-workflow
      version: '1.0.0'
    do:
      - greet:
          set:
            message: '${ "Hello, " + .name + "! Sleeping for 30s..." }'
      - nap:
          wait:
            seconds: 30
      - wakeUp:
          set:
            message: '${ "Done! " + .name + " woke up after sleeping." }'
