---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - logic.kubesmarts.org
  resources:
  - logicflowdefinitions
  - logicflowruntimes
  - logicflowservices
  - logicplatforms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - logic.kubesmarts.org
  resources:
  - logicflowdefinitions/finalizers
  - logicflowruntimes/finalizers
  - logicflowservices/finalizers
  - logicplatforms/finalizers
  verbs:
  - update
- apiGroups:
  - logic.kubesmarts.org
  resources:
  - logicflowdefinitions/status
  - logicflowruntimes/status
  - logicflowservices/status
  - logicplatforms/status
  verbs:
  - get
  - patch
  - update
