## Append samples of your project ##
resources:
- logic_v1_logicplatform.yaml
- logic_v1_logicflowservice.yaml
- logic_v1_logicflowdefinition.yaml
- logic_v1_logicflowruntime.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
