apiVersion: logic.kubesmarts.org/v1
kind: LogicFlowDefinition
metadata:
  labels:
    app.kubernetes.io/name: logic-operator
    app.kubernetes.io/managed-by: kustomize
  name: hello-world-v1-0-0
spec:
  runtimeRef:
    name: hello-runtime
  flow:
    document:
      dsl: '1.0.0'
      namespace: examples
      name: hello-world
      version: '1.0.0'
    do:
      - greet:
          set:
            message: '${ "Hello, " + .name + "!" }'
