apiVersion: logic.kubesmarts.org/v1
kind: LogicFlowService
metadata:
  labels:
    app.kubernetes.io/name: logic-operator
    app.kubernetes.io/managed-by: kustomize
  name: hello-world
spec:
  defaultDefinition:
    name: hello-world-v1-0-0
  ingress:
    host: hello.lvh.me
    ingressClassName: nginx
