apiVersion: logic.kubesmarts.org/v1
kind: LogicFlowDefinition
metadata:
  labels:
    app.kubernetes.io/name: logic-operator
    app.kubernetes.io/managed-by: kustomize
  name: payment-processor-v1-0-0
spec:
  runtimeRef:
    name: payments-runtime
  flow:
    document:
      dsl: '1.0.0'
      namespace: payments
      name: payment-processor
      version: '1.0.0'
    do:
      - validatePayment:
          call: http
          with:
            method: post
            endpoint: https://validation.example.com/api
